const KEYS = {
  whiskies: "example",
};

const whiskyDb = [
  {
    id: 1,
    whisky: `Aberfeldy 12yo`,
    cost: "$$$",
    category: "E",
    type: "Malt",
    tags: [
      "medium-body",
      "semi-sweet",
      "fruity",
      "honey",
      "malty",
      "notes of wine",
      "spicy",
      "light smoke",
    ],
  },
  {
    id: 2,
    whisky: `Aberfeldy 16yo`,
    cost: "$$$$",
    category: "C",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "floral",
      "nutty",
      "spicy",
      "light smoke",
    ],
  },
  {
    id: 3,
    whisky: `Aberfeldy 18yo`,
    cost: "$$$$",
    category: "C",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "floral",
      "nutty",
      "spicy",
      "light smoke",
    ],
  },
  {
    id: 4,
    whisky: `Aberfeldy 21yo`,
    cost: "$$$$$",
    category: "E",
    type: "Malt",
    tags: [
      "medium-body",
      "semi-sweet",
      "fruity",
      "honey",
      "malty",
      "notes of wine",
      "spicy",
      "light smoke",
    ],
  },
  {
    id: 5,
    whisky: `Aberlour 10yo`,
    cost: "$$",
    category: "C",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "floral",
      "nutty",
      "spicy",
      "light smoke",
    ],
  },
  {
    id: 6,
    whisky: `Aberlour 12yo Double Cask Matured`,
    cost: "$$$",
    category: "B",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "floral",
      "malty",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 7,
    whisky: `Aberlour 12yo Non-Chill-Filtered`,
    cost: "$$$",
    category: "B",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "floral",
      "malty",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 8,
    whisky: `Aberlour 16yo Double Cask Matured`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 9,
    whisky: `Aberlour 18yo`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 10,
    whisky: `Aberlour A'Bunadh (all batches)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 11,
    whisky: `Aberlour A'Bunadh (Batch 30)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 12,
    whisky: `Aberlour A'Bunadh (Batch 32)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 13,
    whisky: `Aberlour A'Bunadh (Batch 33)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 14,
    whisky: `Aberlour A'Bunadh (Batch 34)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 15,
    whisky: `Aberlour A'Bunadh (Batch 35)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 16,
    whisky: `Aberlour A'Bunadh (Batch 36)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 17,
    whisky: `Aberlour A'Bunadh (Batch 37)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 18,
    whisky: `Aberlour A'Bunadh (Batch 38)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 19,
    whisky: `Aberlour A'Bunadh (Batch 39)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 20,
    whisky: `Aberlour A'Bunadh (Batch 40)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 21,
    whisky: `Aberlour A'Bunadh (Batch 42)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 22,
    whisky: `Aberlour A'Bunadh (Batch 44)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 23,
    whisky: `Aberlour A'Bunadh (Batch 45)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 24,
    whisky: `Aberlour A'Bunadh (Batch 46)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 25,
    whisky: `Aberlour A'Bunadh (Batch 47)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 26,
    whisky: `Aberlour A'Bunadh (Batch 48)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 27,
    whisky: `Aberlour A'Bunadh (Batch 49)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 28,
    whisky: `Aberlour A'Bunadh (Batch 50)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 29,
    whisky: `Aberlour A'Bunadh (Batch 52)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
  {
    id: 30,
    whisky: `Aberlour A'Bunadh (Batch 53)`,
    cost: "$$$$",
    category: "A",
    type: "Malt",
    tags: [
      "full-body",
      "sweet",
      "pronounced sherry",
      "fruity",
      "honey",
      "spicy",
      "no smoke",
    ],
  },
];

export const getWhiskyDb = () => {
  return JSON.parse(localStorage.getItem(whiskyDb));
};
